### ISSUE TITLE
Improving the performance of the GitHub Actions workflow in the .github/workflows/zip-and-store-cloud-functions.yml file

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#831]
Consider using a caching strategy for your dependencies to speed up your workflow runs. GitHub Actions provides a cache action that you can use to cache dependencies and build outputs to improve workflow execution time.
```yaml
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
```
