### ISSUE TITLE
Adding an index to the 'status' field in the User table can improve the performance of queries that filter on this field.

### ISSUE THREAD

**Issue by steffen74** [eduhub-org/eduhub#832]
Consider adding an index to the 'status' field. This can significantly speed up queries that filter on this field, especially if the table has a large number of records.
```yaml
    indexes:
      - name: idx_status
        columns:
          - status
```
